version: '2'
services:
  php:
    build: ./php/
    volumes:
      - ./php/log:/var/log/php_log
      - ./project:/var/www/html
    links:
      - postgres
      - redis
    environment:
      XDEBUG_CONFIG: "remote_host=10.254.254.254 idekey=myProject remote_enable=1 remote_handler=dbgp remote_port=9000 remote_autostart=1 remote_connect_back=0 remote_log=/var/log/php_log/xdebug.log"
      PHP_IDE_CONFIG: "serverName=test.develop.com"
    restart: always
  nginx:
    build: ./nginx/
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./project:/var/www/html
    links:
      - php
    ports:
      - 8888:80
    restart: always
  postgres:
    build: ./postgres/
    environment:
      - POSTGRES_PASSWORD=rXHW6ULMruNHhEyffhJ8gvRat4F4i2Ly
      - POSTGRES_USER=my-project-postgres
      - POSTGRES_DB=myProject
    ports:
      - 5555:5432
    restart: always
  postgres_backup:
    build: ./pg_backup/
    volumes:
      - ./pg_backup/backup_data:/dump_database
    links:
      - postgres
    restart: always
  redis:
    build: ./redis/
    ports:
      - 9999:6379
    restart: always